# Generated by Django 3.1.7 on 2021-03-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0002_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('original', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
            ],
        ),
    ]
