# Generated by Django 3.1.7 on 2021-03-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Daraz',
        ),
    ]
