# Generated by Django 3.1.7 on 2021-03-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_sastodeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamrobazar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
