# Generated by Django 3.1.7 on 2021-03-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_hamrobazar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daraz',
            name='category',
        ),
    ]
